# Site settings
site_name: "Statinformation"
title: "Экономика и наcеление стран регионов городов исторические данные "
author: "statinformation.ru"
description: "Экономика и наcеление стран регионов городов исторические данные."
keywords: "Экономика и наcеление стран регионов городов исторические данные"
biography:
colophon: "© 2017 - 2022 All Rights Reserved.       Как с нами связаться: (?)"

baseurl: ""
url: "https://statinformation.ru"

twitter_username:
github_username:
linkedin_username:
facebook_username:
google-analytics:

simple_search: http://google.com/search
markdown: kramdown
highlighter: rouge
permalink: /:path.html

collections:
  pages:
   output: true
   permalink: /:path.html

# Plugins
plugins:
  - jekyll-archives
  - jekyll-sitemap

# Plugin archives
jekyll-archives:
  enabled: all
  layout: archive
  permalinks:
    category: '/category/:name/'
